services:
  postgres:
    image: postgres:16
    container_name: task-planner-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: task_planner
      POSTGRES_USER: task_planner
      POSTGRES_PASSWORD: task_planner

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
