"""add projects

Revision ID: 2de7b39fa411
Revises: 49a4fb4f3c93
Create Date: 2026-09-10 16:40:21.469997

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "2de7b39fa411"
down_revision: str | Sequence[str] | None = "49a4fb4f3c93"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
