"""fix user email_verifed

Revision ID: 964ed4b35f5a
Revises: f412c604ecc4
Create Date: 2026-09-10 19:47:57.238146

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "964ed4b35f5a"
down_revision: str | Sequence[str] | None = "f412c604ecc4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
