"""add password reset token

Revision ID: ccf53727dcae
Revises: 9d174578a9c7
Create Date: 2026-09-11 01:04:37.969768

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "ccf53727dcae"
down_revision: str | Sequence[str] | None = "9d174578a9c7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
