"""update user

Revision ID: cd64c6dcf776
Revises: a4df0e2a70dd
Create Date: 2026-09-09 15:52:22.065066

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cd64c6dcf776"
down_revision: str | Sequence[str] | None = "a4df0e2a70dd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "users", sa.Column("nick_name", sa.String(length=255), nullable=False)
    )
    op.add_column(
        "users",
        sa.Column(
            "avatar_url",
            sa.String(length=500),
            server_default="https://i.imgur.com/1yG28tMh.jpg",
            nullable=False,
        ),
    )
    op.add_column("users", sa.Column("email_verified", sa.Boolean(), nullable=False))
    op.create_index(op.f("ix_users_nick_name"), "users", ["nick_name"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_nick_name"), table_name="users")
    op.drop_column("users", "email_verified")
    op.drop_column("users", "avatar_url")
    op.drop_column("users", "nick_name")
    op.drop_column("users", "updated_at")
    # ### end Alembic commands ###
